# WebService ????
server.port=8081
server.ip=127.0.0.1
unique.flag.craft=1000001
unique.flag.order=1000003
target.address.craft=http://localhost:8080/craft/info/getCraftFromMMO
target.address.order=http://localhost:8080/workOrder/getOrderFromMMO