version: '3.8'

networks:
  procvision:
    name: procvision

services:
  # 1. 业务服务 (Server)
  server:
    build: ../src/backend
    container_name: procvision-server
    ports:
      - "8080:8080"
    volumes:
      - ./HikLib:/usr/HikLib
    environment:
      - SPRING_DATASOURCE_HOST=mysql
      - SPRING_REDIS_HOST=redis
      - MINIO_HOST=192.168.80.132
      - MINIO_PORT=9000
      - LD_LIBRARY_PATH=/usr/HikLib:$LD_LIBRARY_PATH
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - procvision

  # 2. 数据库 (MySQL)
  mysql:
    image: mysql:8.0
    container_name: procvision-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: procvision
      MYSQL_INITDB_ARGS: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    restart: unless-stopped
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # 健康检查：检测MySQL是否就绪
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -proot_password -D procvision -e 'SELECT 1 FROM sys_user_role LIMIT 1;'"]
      interval: 10s    # 每5秒检查一次
      timeout: 5s    # 每次检查超时时间10秒
      retries: 20     # 最多重试10次，仍失败则标记为不健康
      start_period: 60s  # 容器启动后，延迟30秒再开始健康检查（给初始化留时间）
    networks:
      - procvision

  # 3. 缓存 (Redis)
  redis:
    image: redis:6.2
    container_name: procvision-redis
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/usr/local/etc/redis
    restart: unless-stopped
    networks:
      - procvision
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  # 4. 对象存储 (MinIO)
  minio:
    image: minio/minio
    container_name: procvision-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    restart: unless-stopped
    volumes:
      - ./minio/data:/data
      - ./minio/config:/etc/minio/config
    command: server /data --config-dir /etc/minio/config --console-address ":9001"
    networks:
      - procvision
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 3

  # 5. 网关 (Nginx)
  front:
    build: ../src/ruoyi-ui
    container_name: procvision-nginx
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - server
    networks:
      - procvision

  # 6. MOM服务 (MOM)
  webservice:
    build: ../MOM/demo
    container_name: procvision-webservice
    ports:
      - "8083:8080"
    restart: unless-stopped
    depends_on:
      - server
    environment:
      SERVER_PORT: 8083
      SERVER_IP: server
      TARGET_SERVER_CRAFT: http://localhost:8080/craft/info/getCraftFromMMO
      TARGET_SERVER_ORDER: http://localhost:8080/workOrder/getOrderFromMMO
    networks:
      - procvision